require('dotenv').config();
const express = require('express');
const cors = require('cors');
const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);
const Anthropic = require('@anthropic-ai/sdk');
const PDFDocument = require('pdfkit');
const multer = require('multer');
const AdmZip = require('adm-zip');
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 50 * 1024 * 1024 } });

const app = express();
const PORT = process.env.PORT || 3001;

// Only init Anthropic if key is valid (not placeholder from .env.example)
const _apiKey = process.env.ANTHROPIC_API_KEY || '';
const _hasValidKey = _apiKey && _apiKey !== 'sk-ant-...' && _apiKey.startsWith('sk-ant-api');
const anthropic = _hasValidKey ? new Anthropic({ apiKey: _apiKey }) : null;

app.use('/webhook', express.raw({ type: 'application/json' }));
app.use(express.json());
app.use(cors({ origin: process.env.FRONTEND_URL || '*' }));

app.get('/health', (req, res) => res.json({ status: 'ok', service: 'manualos-backend', aiEnabled: _hasValidKey }));

app.post('/create-checkout-session', async (req, res) => {
    try {
        const { email } = req.body;
        const session = await stripe.checkout.sessions.create({
            payment_method_types: ['card'],
            mode: 'subscription',
            line_items: [{ price: process.env.STRIPE_PRICE_ID, quantity: 1 }],
            customer_email: email,
            success_url: process.env.FRONTEND_URL + '/success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url: process.env.FRONTEND_URL + '/cancel',
        });
        res.json({ url: session.url });
    } catch (err) {
        console.error('Checkout error:', err);
        res.status(500).json({ error: err.message });
    }
});

app.get('/verify-session', async (req, res) => {
    try {
        const { session_id } = req.query;
        const session = await stripe.checkout.sessions.retrieve(session_id, { expand: ['subscription', 'customer'] });
        res.json({ paid: session.payment_status === 'paid', customer: session.customer_details, subscription: session.subscription });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

function calculateCodeReferencePercentage(plcContent, manualText) {
    if (!plcContent || !manualText) return 0;
    const tokenRegex = /\b([A-Za-z_][A-Za-z0-9_]{2,})\b/g;
    const plcTokens = new Set();
    let match;
    while ((match = tokenRegex.exec(plcContent)) !== null) {
        const token = match[1].toLowerCase();
        const skip = new Set(['var','end','for','the','and','not','int','bool','true','false','then','else','begin','function','program','type','struct','array','real','word','byte','string']);
        if (!skip.has(token)) plcTokens.add(token);
    }
    if (plcTokens.size === 0) return 0;
    const manualLower = manualText.toLowerCase();
    let referenced = 0;
    for (const token of plcTokens) { if (manualLower.includes(token)) referenced++; }
    return Math.min(Math.round((referenced / plcTokens.size) * 100), 100);
}

function extractPlcInfo(xml) {
    const info = { controller:'', programs:[], tasks:[], routines:[], tags:[], modules:[] };
    const ctrlM = xml.match(/<Controller[^>]*Name="([^"]+)"/i);
    if (ctrlM) info.controller = ctrlM[1];
    for (const m of xml.matchAll(/<Task[^>]*Name="([^"]+)"[^>]*(?:Period="([^"]*)")?[^>]*(?:Priority="([^"]*)")?/gi)) info.tasks.push({name:m[1],period:m[2]||'',priority:m[3]||''});
    for (const m of xml.matchAll(/<Program[^>]*Name="([^"]+)"/gi)) { if (!info.programs.includes(m[1])) info.programs.push(m[1]); }
    for (const m of xml.matchAll(/<Routine[^>]*Name="([^"]+)"[^>]*(?:Type="([^"]*)")?/gi)) info.routines.push({name:m[1],type:m[2]||'Ladder'});
    let tc=0; for (const m of xml.matchAll(/<Tag[^>]*Name="([^"]+)"[^>]*DataType="([^"]+)"[^>]*(?:Description="([^"]*)")?/gi)) { if(tc++>=50)break; info.tags.push({name:m[1],type:m[2],desc:m[3]||''}); }
    for (const m of xml.matchAll(/<Module[^>]*Name="([^"]+)"[^>]*(?:CatalogNumber="([^"]*)")?/gi)) info.modules.push({name:m[1],catalog:m[2]||''});
    return info;
}

function generateTemplateManual(plcContent, brand, filename) {
    const info = extractPlcInfo(plcContent);
    const ctrl = info.controller || filename || 'PLC System';
    const br = brand || 'Unknown';
    const date = new Date().toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'});
    let t = 'OPERATOR MANUAL\n' + ctrl + '\n' + br + ' PLC System\nGenerated by ManualOS | ' + date + '\n\n';
    t += '================================================================================\n1. SYSTEM OVERVIEW\n================================================================================\n\n';
    t += 'This manual covers the ' + ctrl + ' PLC system manufactured by ' + br + '.\n';
    t += 'File: ' + (filename||'N/A') + ' | Programs: ' + (info.programs.join(', ')||'N/A') + '\n\n';
    t += '================================================================================\n2. SAFETY WARNINGS\n================================================================================\n\n';
    t += 'WARNING: De-energize and LOTO all power before any maintenance work.\n';
    t += 'DANGER: High voltage present - only qualified personnel may work on this system.\n';
    t += 'CAUTION: Verify safe state before making program changes or forcing I/O.\n\n';
    if (info.tasks.length) {
        t += '================================================================================\n3. TASKS\n================================================================================\n';
        for (const k of info.tasks) t += 'Task: ' + k.name + (k.period?' Period:'+k.period+'ms':'') + (k.priority?' Priority:'+k.priority:'') + '\n';
        t += '\n';
    }
    if (info.programs.length) {
        t += '================================================================================\n4. PROGRAMS\n================================================================================\n';
        for (const p of info.programs) t += '  - ' + p + '\n';
        t += '\n';
    }
    if (info.routines.length) {
        t += '================================================================================\n5. ROUTINES\n================================================================================\n';
        for (const r of info.routines) t += '  - ' + r.name + ' (' + r.type + ')\n';
        t += '\n';
    }
    if (info.modules.length) {
        t += '================================================================================\n6. MODULES\n================================================================================\n';
        for (const m of info.modules) t += '  ' + m.name + (m.catalog?' ('+m.catalog+')':'') + '\n';
        t += '\n';
    }
    if (info.tags.length) {
        t += '================================================================================\n7. TAG REFERENCE\n================================================================================\n';
        for (const g of info.tags) t += '  ' + g.name + ' (' + g.type + ')' + (g.desc?' - '+g.desc:'') + '\n';
        t += '\n';
    }
    t += '================================================================================\n8. OPERATING PROCEDURES\n================================================================================\n\n';
    t += 'STARTUP:\n1. Verify safety interlocks functional\n2. Check I/O connections\n3. Power on, verify RUN indicator\n4. Clear all faults\n5. Enable outputs via operator interface\n\n';
    t += 'NORMAL OPERATION:\n- Monitor system via HMI\n- Respond to alarms promptly\n- Log unusual behavior\n\n';
    t += 'SHUTDOWN:\n1. Initiate controlled shutdown via operator interface\n2. Verify outputs de-energized\n3. Apply LOTO before maintenance\n\n';
    t += '================================================================================\n9. TROUBLESHOOTING\n================================================================================\n\n';
    t += 'CONTROLLER FAULT: Check fault code, review recent changes, verify I/O comms\n';
    t += 'I/O COMM ERROR: Check cables, power supplies, node addresses\n';
    t += 'LOGIC ERROR: Review ladder logic, check tag values online, verify sensors\n\n';
    t += '================================================================================\n10. MAINTENANCE SCHEDULE\n================================================================================\n\n';
    t += 'DAILY: Check status LEDs, review alarm history\n';
    t += 'WEEKLY: Inspect connections, backup program to maintenance folder\n';
    t += 'MONTHLY: Clean panel (LOTO), check battery backup\n';
    t += 'ANNUALLY: Full functional test, calibration verification, update documentation\n\n';
    t += 'Generated by ManualOS AI Manual Generator.\n';
    return t;
}

function generatePDF(manualText, brand, codeRefPercentage) {
  return new Promise((resolve, reject) => {
    // Colors
    const C = { primary: '#1a3a5c', accent: '#e8f4f8', gold: '#c8a500', warn: '#d44000', danger: '#b00000', caution: '#e67e00', body: '#222', light: '#f7f9fb', border: '#c5d5e0', white: '#ffffff', muted: '#5a6a7a' };
    const doc = new PDFDocument({ margin: 0, size: 'LETTER', info: { Title: 'PLC Operator Manual', Author: 'ManualOS', Creator: 'ManualForge AI' } });
    const buffers = [];
    doc.on('data', chunk => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    const W = doc.page.width;
    const H = doc.page.height;
    const ML = 54, MR = 54, MT = 50;
    const CW = W - ML - MR;

    // ---- HELPER FUNCTIONS ----
    function hexToRgb(hex) {
      const r = parseInt(hex.slice(1,3),16);
      const g = parseInt(hex.slice(3,5),16);
      const b = parseInt(hex.slice(5,7),16);
      return [r, g, b];
    }
    function setFill(hex) { const [r,g,b]=hexToRgb(hex); doc.fillColor([r,g,b]); }
    function setStroke(hex) { const [r,g,b]=hexToRgb(hex); doc.strokeColor([r,g,b]); }

    function drawPageHeader(title) {
      doc.rect(0, 0, W, 38).fill(hexToRgb(C.primary));
      doc.fillColor(hexToRgb(C.white)).fontSize(9).font('Helvetica-Bold').text('MANUALOS', ML, 13, { width: CW/2 });
      doc.fillColor(hexToRgb(C.white)).fontSize(9).font('Helvetica').text(title, ML + CW/2, 13, { width: CW/2, align: 'right' });
    }

    function drawPageFooter(pageNum) {
      const y = H - 30;
      doc.moveTo(ML, y - 4).lineTo(W - MR, y - 4).stroke(hexToRgb(C.border));
      doc.fillColor(hexToRgb(C.muted)).fontSize(8).font('Helvetica')'ManualOS AI-Generated Documentation (.text For reference only. Verify all safety-critical information.', ML, y, { width: CW - 60 });
      doc.fillColor(hexToRgb(C.muted)).fontSize(8).text('Page ' + pageNum, ML, y, { width: CW, align: 'right' });
    }

    function sectionHeader(label, y, color) {
      color = color || C.primary;
      doc.rect(ML, y, CW, 26).fill(hexToRgb(color));
      doc.fillColor(hexToRgb(C.white)).fontSize(12).font('Helvetica-Bold').text(label, ML + 12, y + 7, { width: CW - 20 });
      return y + 30;
    }

    function checkY(y, needed) {
      needed = needed || 60;
      if (y + needed > H - 50) {
        doc.addPage();
        drawPageHeader(currentSection);
        drawPageFooter(++pageNum);
        return MT + 40;
      }
      return y;
    }

    function infoBox(x, y, w, h, bg, border) {
      doc.rect(x, y, w, h).fill(hexToRgb(bg || C.accent));
      if (border) { doc.rect(x, y, w, h).stroke(hexToRgb(border)); }
      return y;
    }

    function warningBox(type, text, y) {
      const colors = { WARNING: [C.warn, '#fff4ef'], DANGER: [C.danger, '#fff0f0'], CAUTION: [C.caution, '#fffaf0'], NOTE: [C.primary, C.accent] };
      const [bc, bg] = colors[type] || colors.NOTE;
      const lineH = 14;
      const lines = text.match(/.{1,85}/g) || [text];
      const bh = 10 + lines.length * lineH + 6;
      y = checkY(y, bh + 8);
      doc.rect(ML, y, 4, bh).fill(hexToRgb(bc));
      doc.rect(ML + 4, y, CW - 4, bh).fill(hexToRgb(bg));
      doc.rect(ML + 4, y, CW - 4, bh).stroke(hexToRgb(bc));
      doc.fillColor(hexToRgb(bc)).fontSize(8).font('Helvetica-Bold').text(type + ':', ML + 14, y + 7);
      doc.fillColor(hexToRgb(C.body)).fontSize(9.5).font('Helvetica').text(text, ML + 14 + 52, y + 7, { width: CW - 70 });
      return y + bh + 6;
    }

    function tableHeader(cols, widths, y) {
      y = checkY(y, 30);
      doc.rect(ML, y, CW, 22).fill(hexToRgb(C.primary));
      let x = ML + 6;
      cols.forEach((col, i) => {
        doc.fillColor(hexToRgb(C.white)).fontSize(9).font('Helvetica-Bold').text(col, x, y + 6, { width: widths[i] - 4, lineBreak: false });
        x += widths[i];
      });
      return y + 22;
    }

    function tableRow(cells, widths, y, isEven) {
      const rh = 18;
      y = checkY(y, rh);
      doc.rect(ML, y, CW, rh).fill(hexToRgb(isEven ? C.accent : C.white));
      doc.rect(ML, y, CW, rh).stroke(hexToRgb(C.border));
      let x = ML + 6;
      cells.forEach((cell, i) => {
        doc.fillColor(hexToRgb(C.body)).fontSize(8.5).font('Helvetica').text(String(cell||'').substring(0,60), x, y + 4, { width: widths[i] - 8, lineBreak: false });
        x += widths[i];
      });
      return y + rh;
    }

    // ---- PARSE MANUAL TEXT INTO SECTIONS ----
    const lines = manualText.split('\n');
    let pageNum = 1;
    let currentSection = 'Overview';

    // Extract title info from first lines
    const titleLine = lines[0] || 'OPERATOR MANUAL';
    const controllerLine = lines[1] || '';
    const brandLine = lines[2] || brand || '';

    // =========================================
    // PAGE 1: COVER
    // =========================================
    // Top dark band
    doc.rect(0, 0, W, 220).fill(hexToRgb(C.primary));
    // Gold accent line
    doc.rect(0, 220, W, 5).fill(hexToRgb(C.gold));
    // White content area
    doc.rect(0, 225, W, H - 225).fill(hexToRgb(C.white));

    // Cover logo area
    doc.fillColor(hexToRgb(C.white)).fontSize(36).font('Helvetica-Bold').text('MANUALOS', 0, 55, { align: 'center', width: W });
    doc.fillColor(hexToRgb(C.gold)).fontSize(13).font('Helvetica').text('AI-POWERED DOCUMENTATION', 0, 96, { align: 'center', width: W });

    // Horizontal divider in header
    doc.moveTo(ML, 124).lineTo(W - MR, 124).strokeColor(hexToRgb(C.gold)).lineWidth(0.5).stroke();

    // Document type
    doc.fillColor(hexToRgb(C.white)).fontSize(10).font('Helvetica').text('OPERATOR MANUAL', 0, 135, { align: 'center', width: W });

    // Equipment details box
    const bx = ML + 20, bw = CW - 40, by = 250;
    doc.rect(bx, by, bw, 130).fill(hexToRgb(C.light));
    doc.rect(bx, by, bw, 130).stroke(hexToRgb(C.border));
    doc.rect(bx, by, 4, 130).fill(hexToRgb(C.primary));

    // Controller / system name
    const sysName = controllerLine || (lines.find(l => l.match(/controller|system|plc/i)) || controllerLine || 'PLC SYSTEM');
    doc.fillColor(hexToRgb(C.muted)).fontSize(9).font('Helvetica').text('SYSTEM / CONTROLLER', bx + 20, by + 18);
    doc.fillColor(hexToRgb(C.primary)).fontSize(18).font('Helvetica-Bold').text(sysName.substring(0, 50), bx + 20, by + 32, { width: bw - 40 });
    doc.fillColor(hexToRgb(C.muted)).fontSize(9).font('Helvetica').text('MANUFACTURER', bx + 20, by + 70);
    doc.fillColor(hexToRgb(C.body)).fontSize(12).font('Helvetica-Bold').text(brandLine || brand || 'N/A', bx + 20, by + 83);
    doc.fillColor(hexToRgb(C.muted)).fontSize(9).font('Helvetica').text('DATE GENERATED', bx + 20, by + 105);
    doc.fillColor(hexToRgb(C.body)).fontSize(10).font('Helvetica').text(new Date().toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'}), bx + 20, by + 118);

    // Code reference percentage badge
    if (codeRefPercentage > 0) {
      const bpx = W - MR - 100, bpy = by + 25;
      doc.rect(bpx, bpy, 80, 80).fill(hexToRgb(C.primary));
      doc.fillColor(hexToRgb(C.white)).fontSize(26).font('Helvetica-Bold').text(codeRefPercentage+'%', bpx, bpy + 14, { width: 80, align: 'center' });
      doc.fillColor(hexToRgb(C.gold)).fontSize(7).font('Helvetica').text('CODE REFERENCE', bpx, bpy + 50, { width: 80, align: 'center' });
      doc.fillColor(hexToRgb(C.gold)).fontSize(7).font('Helvetica').text('COVERAGE', bpx, bpy + 60, { width: 80, align: 'center' });
    }

    // Footer notice on cover
    doc.fillColor(hexToRgb(C.muted)).fontSize(8).font('Helvetica-Oblique').text('This document was generated by ManualOS AI. Verify all safety-critical information against official documentation before use.', ML, H - 60, { width: CW, align: 'center' });

    // =========================================
    // PAGE 2+: CONTENT
    // =========================================
    doc.addPage();
    pageNum++;
    currentSection = 'Overview';
    drawPageHeader(currentSection);
    drawPageFooter(pageNum);

    let y = MT + 45;

    // Parse sections from manual text
    let inSection = '';
    let sectionBuf = [];
    const sections = [];

    for (let i = 4; i < lines.length; i++) {
      const line = lines[i];
      const isSep = line.startsWith('===') || line.startsWith('---');
      const isHdr = line.match(/^[0-9]+.[s]/);
      if (isSep && i + 1 < lines.length && lines[i+1].match(/^[0-9]+./)) continue;
      if (isHdr || (isSep && sectionBuf.length > 0)) {
        if (inSection) sections.push({ title: inSection, lines: sectionBuf });
        inSection = line.replace(/^[0-9]+.s+/, '').replace(/=+/g,'').trim();
        sectionBuf = [];
      } else {
        sectionBuf.push(line);
      }
    }
    if (inSection) sections.push({ title: inSection, lines: sectionBuf });

    // If no structured sections found, fall back to raw text rendering
    if (sections.length === 0) {
      for (let i = 4; i < lines.length; i++) {
        sectionBuf.push(lines[i]);
      }
      sections.push({ title: 'Manual Content', lines: sectionBuf });
    }

    // Render each section
    for (const sec of sections) {
      y = checkY(y, 60);
      currentSection = sec.title;

      // Detect section type for styling
      const isSafety = /safety|warning|danger|hazard/i.test(sec.title);
      const isTag = /tag|reference/i.test(sec.title);
      const isTask = /task/i.test(sec.title);
      const isModule = /module|hardware/i.test(sec.title);
      const isRoutine = /routine/i.test(sec.title);
      const isProgram = /program/i.test(sec.title);
      const isOp = /operat/i.test(sec.title);

      const hColor = isSafety ? C.danger : C.primary;
      y = sectionHeader(sec.title.toUpperCase(), y, hColor);
      y += 6;

      // Detect and render table-like sections
      if (isTag && sec.lines.some(l => l.match(/(BOOL|DINT|REAL|INT|UDINT|STRING/))) {
        // Tag table
        const widths = [200, 80, CW - 280];
        y = tableHeader(['Tag Name', 'Data Type', 'Description'], widths, y);
        let rowN = 0;
        for (const l of sec.lines) {
          const m = l.match(/([w.]+)s*(([w]+))(s*-s*(.*))?/);
          if (m) { y = tableRow([m[1], m[2], m[4]||''], widths, y, rowN % 2 === 0); rowN++; }
        }
      } else if ((isTask || isModule || isRoutine || isProgram) && sec.lines.some(l => l.match(/^s*[-*]|^Task:|^w/))) {
        // Two-column list table
        const widths = [CW/2, CW/2];
        y = tableHeader(['Name', 'Details'], widths, y);
        let rowN = 0;
        for (const l of sec.lines) {
          const clean = l.replace(/^s*[-*]s*/, '').trim();
          if (!clean) continue;
          const parts = clean.split(/:s*|s{2,}/);
          y = tableRow([parts[0]||'', parts.slice(1).join(' ')||''], widths, y, rowN % 2 === 0);
          rowN++;
        }
      } else if (isSafety) {
        // Safety section: parse warning/danger/caution lines specially
        for (const l of sec.lines) {
          if (!l.trim()) { y += 4; continue; }
          y = checkY(y, 30);
          if (/^WARNING:/i.test(l)) { y = warningBox('WARNING', l.replace(/^WARNING:s*/i,''), y); }
          else if (/^DANGER:/i.test(l)) { y = warningBox('DANGER', l.replace(/^DANGER:s*/i,''), y); }
          else if (/^CAUTION:/i.test(l)) { y = warningBox('CAUTION', l.replace(/^CAUTION:s*/i,''), y); }
          else if (/^NOTE:/i.test(l)) { y = warningBox('NOTE', l.replace(/^NOTE:s*/i,''), y); }
          else {
            doc.fillColor(hexToRgb(C.body)).fontSize(10).font('Helvetica').text(l, ML, y, { width: CW, lineGap: 2 });
            y += doc.heightOfString(l, { width: CW }) + 4;
          }
        }
      } else {
        // General prose content
        for (const l of sec.lines) {
          y = checkY(y, 16);
          if (!l.trim()) { y += 5; continue; }
          const isBullet = /^s*[-*]/.test(l);
          const isSubHdr = l.match(/^[A-Z][A-Zs]{4,}:/) || l.match(/^[A-Zs]{5,}$/);
          if (isSubHdr) {
            y += 4;
            doc.fillColor(hexToRgb(C.primary)).fontSize(10).font('Helvetica-Bold').text(l.trim(), ML, y, { width: CW });
            y += 14;
          } else if (isBullet) {
            doc.fillColor(hexToRgb(C.primary)).text('•', ML + 8, y, { width: 14, lineBreak: false });
            doc.fillColor(hexToRgb(C.body)).fontSize(10).font('Helvetica').text(l.replace(/^s*[-*]s*/,'').trim(), ML + 22, y, { width: CW - 22, lineGap: 2 });
            y += doc.heightOfString(l, { width: CW - 22 }) + 3;
          } else {
            doc.fillColor(hexToRgb(C.body)).fontSize(10).font('Helvetica').text(l, ML, y, { width: CW, lineGap: 2 });
            y += doc.heightOfString(l, { width: CW }) + 3;
          }
        }
      }
      y += 14;
    }

    doc.end();
  });
}
app.post('/generate-manual', upload.single('file'), async (req, res) => {
    // Extend socket timeout to prevent Railway proxy 60s timeout
    if (req.socket) req.socket.setTimeout(0);
    res.setTimeout(0);
    try {
        let plcContent = '';
        const brand = (req.body && req.body.brand) || '';
        const sections = (req.body && req.body.sections) ? JSON.parse(req.body.sections) : [];
        const filename = req.file ? req.file.originalname : 'unknown.acd';
        if (req.file) {
            const fileExt = req.file.originalname.split('.').pop().toLowerCase();
            if (fileExt === 'acd' || fileExt === 'zip' || fileExt === 'zap15') {
                try {
                    const zip = new AdmZip(req.file.buffer);
                    const zipEntries = zip.getEntries();
                    const xmlEntries = zipEntries.filter(e => e.entryName.endsWith('.xml') || e.entryName.endsWith('.L5X') || e.entryName.endsWith('.l5x'));
                    if (xmlEntries.length > 0) {
                        xmlEntries.sort((a, b) => b.header.size - a.header.size);
                        plcContent = zip.readAsText(xmlEntries[0]);
                        if (plcContent.length > 200000) plcContent = plcContent.substring(0, 200000) + '\n... [truncated]';
                    } else {
                        plcContent = 'ACD Binary File: ' + req.file.originalname + ' - ' + req.file.size + ' bytes. Entries: ' + zipEntries.map(e=>e.entryName).join(', ');
                    }
                } catch (zipErr) {
                    // ACD files may use a format adm-zip can't read. Try scanning buffer for raw XML.
                    console.error('ZIP error:', zipErr.message);
                    try {
                      const bufStr = req.file.buffer.toString('latin1');
                      const xmlStart = bufStr.indexOf('<RSLogix5000Content');
                      const xmlStart2 = bufStr.indexOf('<?xml');
                      const start = xmlStart >= 0 ? xmlStart : (xmlStart2 >= 0 ? xmlStart2 : -1);
                      if (start >= 0) {
                        const xmlEnd = bufStr.lastIndexOf('</RSLogix5000Content>');
                        plcContent = xmlEnd >= 0 ? bufStr.substring(start, xmlEnd + 21) : bufStr.substring(start, start + 200000);
                        if (plcContent.length > 200000) plcContent = plcContent.substring(0, 200000) + '\n... [truncated]';
                        console.log('Extracted XML from raw buffer, length:', plcContent.length);
                      } else {
                        plcContent = 'ACD Binary File: ' + req.file.originalname + ' - ' + req.file.size + ' bytes.';
                      }
                    } catch(e2) {
                      plcContent = 'ACD Binary File: ' + req.file.originalname + ' - ' + req.file.size + ' bytes.';
                    }
                  }
            } else {
                plcContent = req.file.buffer.toString('utf8');
            }
        } else if (req.body && req.body.plcContent) {
            plcContent = req.body.plcContent;
        }
        if (!plcContent) return res.status(400).json({ error: 'No file or plcContent provided' });

        let manualText = '';
        let usedAI = false;

        if (_hasValidKey && anthropic) {
            try {
                console.log('Calling Anthropic API...');
                const prompt = 'You are an expert industrial automation engineer. Generate a comprehensive operator manual for the following PLC program.\n\nBrand/Manufacturer: ' + (brand||'Unknown') + '\nSections: ' + (sections.join(', ')||'All standard') + '\n\nPLC Content:\n' + plcContent + '\n\nGenerate a professional operator manual with safety warnings and operational procedures.';
                const message = await anthropic.messages.create({ model: 'claude-3-5-haiku-20241022', max_tokens: 4096, messages: [{ role: 'user', content: prompt }] });
                manualText = message.content[0].text;
                usedAI = true;
                console.log('Anthropic API success.');
            } catch (aiErr) {
                console.error('Anthropic failed, using template:', aiErr.message);
                manualText = generateTemplateManual(plcContent, brand, filename);
            }
        } else {
            console.log('No valid Anthropic key - template generation.');
            manualText = generateTemplateManual(plcContent, brand, filename);
        }

        const codeRefPercentage = calculateCodeReferencePercentage(plcContent, manualText);
        const pdfBuffer = await generatePDF(manualText, brand, codeRefPercentage);
        res.set({
            'Content-Type': 'application/pdf',
            'Content-Disposition': 'attachment; filename="matrix-manual-report.pdf"',
            'Content-Length': pdfBuffer.length,
            'X-Manual-Mode': usedAI ? 'ai-generated' : 'template-generated',
        });
        res.send(pdfBuffer);
    } catch (err) {
        console.error('Manual generation error:', err);
        res.status(500).json({ error: err.message, stack: err.stack });
    }
});

app.post('/webhook', async (req, res) => {
    const sig = req.headers['stripe-signature'];
    let event;
    try {
        event = stripe.webhooks.constructEvent(req.body, sig, process.env.STRIPE_WEBHOOK_SECRET);
    } catch (err) {
        return res.status(400).send('Webhook signature verification failed');
    }
    switch (event.type) {
        case 'checkout.session.completed': console.log('Payment completed:', event.data.object.customer_email); break;
        case 'customer.subscription.created': console.log('Subscription created:', event.data.object); break;
        case 'customer.subscription.deleted': console.log('Subscription cancelled:', event.data.object); break;
        case 'invoice.payment_failed': console.log('Payment failed:', event.data.object.customer_email); break;
        default: console.log('Unhandled event:', event.type);
    }
    res.json({ received: true });
});

app.listen(PORT, () => console.log('ManualOS backend running on port ' + PORT));
